### ISSUE TITLE
contributions?

### ISSUE THREAD

**Issue by jasonkuhrt** [saschagehlich/npm-yaml#1]
Are you open to contributions? There are 3 things I'd like to do:
- yaml parsing error feedback
- also allow `.yaml` (and make `.yaml` default)
- use 2 spaces, not 4, for json indentation

Also maybe rewrite it in coffeescript...?

**Comment by saschagehlich** [comment]
Sure, feel free to fork and contribute! :)

**Comment by jasonkuhrt** [comment]
Cheers
